name: Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: sudo docker run -v $(pwd):/app/tus terminusdb/swipl:latest swipl -g run_tests -g halt /app/tus/prolog/tus.pl
